language: node_js
node_js: stable

cache:
  directories:
    - "node_modules"

# branches:
#   only:
#     - main

install:
  - yarn

script:
  - yarn docs:build
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target-branch: gh-pages
  local-dir: .vuepress/dist
  on:
    branches:    # ← new!
          only:      # ← new!
            - master # ← new!